env:
  PACKAGE_NAME: unnamed

name: Build and Release LaTeX Package
# This should be triggered for a tagged release, such as:
# git tag v1.0.0
# git push origin v1.0.0
# (to only push tags)
# or git push --tags
# (to push all commits and tags)
on:
  push:
    tags:
      - 'v*'
      # - v[0-9]+(\.[0-9]+)*([-\.]\S+)?
jobs:
  build:
    # if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Set up TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        repository: http://ctan.math.utah.edu/tex-archive/systems/texlive/tlnet
        packages: >-
          latex-bin
          latexmk
          scheme-basic
          catchfile
          silence
          # filecontents
    - name: Generate .sty from .ins
      # if: ${{ runner.os == 'Linux' }}
      run: pdflatex $PACKAGE_NAME.ins
    - name: Upload .sty as artifact
      # if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}-sty
        path: ${{ env.PACKAGE_NAME }}.sty
    - name: Create CTAN zip bundle
      run: zip $PACKAGE_NAME.zip $PACKAGE_NAME.dtx $PACKAGE_NAME.ins $PACKAGE_NAME.sty
    - name: Create GitHub release
      # uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      # with:
      #   files: |
      #     ${{ env.PACKAGE_NAME }}.sty
      #     ${{ env.PACKAGE_NAME }}.dtx
      #     ${{ env.PACKAGE_NAME }}.ins
      #     README.md
      env:
        GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
      run: >-
        gh release create ${{ github.ref_name }}
        "$PACKAGE_NAME.zip"
        --generate-notes
        --title "Version ${{ github.ref_name }}"
